stages:
  - check-tag
  - build-and-push

check_tag:
  stage: check-tag
  script:
    - echo "Checking for release tag..."
    - TAG_NAME="${CI_COMMIT_TAG}"
    - if [ -z "$TAG_NAME" ]; then echo "No tag found on this commit." && exit 1; fi
    - echo "TAG_NAME=$TAG_NAME" > tag_output.env
  artifacts:
    reports:
      dotenv: tag_output.env
  only:
    - releases

build_and_push:
  stage: build-and-push
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker buildx create --use
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker buildx build --push --tag "$DOCKER_USER/onepiece-app:latest" --platform linux/amd64,linux/arm64 ./website
    - docker buildx build --push --tag "$DOCKER_USER/onepiece-app:$CI_COMMIT_TAG" --platform linux/amd64,linux/arm64 ./website
  only:
    - releases