stages:
  - check-tag
  - build-and-push

check_tag:
  stage: check-tag
  script:
    - echo "Checking for release tag..."
    - TAG_NAME="${CI_COMMIT_TAG}"
    - if [ -z "$TAG_NAME" ]; then echo "No tag found on this commit." && exit 1; fi
    - echo "TAG_NAME=$TAG_NAME" > tag_output.env
  artifacts:
    reports:
      dotenv: tag_output.env

build_and_push:
  stage: build-and-push
  needs:
    - check_tag
  script:
    - git submodule update --init --recursive
    - docker buildx create --use
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker buildx build --push --tag "$DOCKER_USER/onepiece-app:latest" --tag "$DOCKER_USER/onepiece-app:$TAG_NAME" --platform linux/amd64,linux/arm64 ./website
  only:
    - tags