apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-db
  namespace: {{ .Values.namespace }}
spec:
    egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ .Values.namespacedb }}
    ingress:
    - ports:
      - port: {{ .Values.onepieceapp.port }}
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
kind: List
metadata:
  resourceVersion: ""          