apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apps-to-db
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}  # Aplica-se a todos os pods no namespace db
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespacedb }}
      ports:
        - protocol: TCP
          port: 3306