apiVersion: v1
kind: Secret
metadata:
  name: onepiece-db-secret
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.onepieceapp.usernamedb | default "" | b64enc | quote }}
  password: {{ .Values.onepieceapp.passwordb | default "" | b64enc | quote }}
  hostaddrdb: {{ .Values.onepieceapp.hostaddrdb | default "" | b64enc | quote }}
  databasename: {{ .Values.onepieceapp.databasename | default "" | b64enc | quote }}