apiVersion: v1
kind: Secret
metadata:
  name: onepiece-db-secret
  namespace: {{ .Values.namespace }}
data:
  usernamedb: {{ .Values.onepieceapp.dbaccess.usernamedb | b64enc | quote }}
  passwordb: {{ .Values.onepieceapp.dbaccess.passwordb | b64enc | quote }}
  hostaddrdb: {{ .Values.onepieceapp.dbaccess.hostaddrdb | b64enc | quote }}
  databasename: {{ .Values.onepieceapp.dbaccess.databasename| b64enc | quote }}