namespace: "onepiece"
namespacedb: "db"
env: "prod"

onepieceapp:
  replicaCount: 1
  image:
    repository: feliperibeiro95/onepiece-app
    tag: "2.2"
  port: 5000
  serviceName: onepieceapp
  livenessProbe:
    execCommand: 
      - wget
      - -T2
      - -O-
      - onepieceapp:5000
    failureThreshold: 3
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1
    usernamedb: ""
    passwordb: ""
    hostaddrdb: ""
    databasename: ""

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  ingressClassName: "nginx"
  rewriteTarget: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "onepiece2.felipeduribeiro.com.br"
      paths:
        - path: /
          pathType: Prefix
          service: onepieceapp
          port: 5000
  tls:
    enabled: true
    config:
      - hosts:
          - "onepiece2.felipeduribeiro.com.br"
        secretName: onepiece-cert
