apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: onepiece-app
  name: onepiece-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepiece-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: onepiece-app
    spec:
      containers:
      - image: feliperibeiro95/onepiece-app:1.1
        name: onepiece-app
        resources: {}
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "onepiece-db"
        - name: MYSQL_PASSWORD
          value: "opwq9021"
        - name: MYSQL_DB
          value: "onepiece"
        - name: MYSQL_USER
          value: "root"
status: {}
